on: 
  push:
    branches:
    - master
    paths:
    - 'policytests/*.yaml'
name: Validate
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: calico-policy-test
      uses: instrumenta/conftest-action@master
      with:
        files: calicopolicy.yaml
        path: ./policytests
        policy: ./policytests/policy

