on: 
  push:
    branches:
    - 'team*'
    paths:
    - 'policytests/calicopolicy.yaml'
name: Validate
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: calico-policy-test
      uses: instrumenta/conftest-action@master
      with:
        files: ./policytests/calicopolicy.yaml
        policy: ./policytests/policy

